movie/urls.py
from django.urls import path
from . import views

app_name = "movie"

urlpatterns = [
    path('', views.home, name="home"),
    path('details/<int:id>/', views.details, name="details"),
    path('addmovies/', views.add_movie, name="add_movie"),
    path('updatemovies/<int:id>/', views.update_movie, name="update_movie"),
    path('deletemovies/<int:id>/', views.delete_movie, name="delete_movie"),
    path('addreview/<int:id>/', views.add_review, name="add_review"),
    path('editreview/<int:movie_id>/<int:review_id>/', views.edit_review, name="edit_review"),
    path('deletereview/<int:movie_id>/<int:review_id>/', views.delete_review, name="delete_review"),
    path('watchlistadd/<int:movie_id>/', views.watchlist_add, name="watchlist_add"),
    path('watchlistdel/<int:movie_id>/', views.watchlist_del, name="watchlist_del"),
    path('watchlistview/', views.watchlist_view, name="watchlist_view"),


]

moviereview/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),
    path('user/', include('user.urls')),
    
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
   path('register/', views.register, name="register"),
   path('login/', views.login_user, name="login"),
   path('logout/', views.user_logout, name="logout"),
]

movie/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Movie(models.Model):
    name = models.CharField(max_length=300)
    director = models.CharField(max_length=50)
    cast = models.CharField(max_length=1000)
    description = models.TextField(max_length=5000)
    category = models.CharField(max_length=100,null=True)
    rel_date = models.DateField()
    avg_rating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)

    def __str__(self):
        return self.name
    
    def __unicode__(self):
        return self.name

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    comment = models.TextField(max_length=10000)
    rating = models.FloatField(default=0)
    
    def __str__(self):
        return self.user.username

class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ManyToManyField(Movie)
    
    def __str__(self):
        return f"{self.user}'s WatchList"

movie/forms.py
from django import forms
from .models import *

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'director', 'cast', 'description', 'category', 'rel_date','image')

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('comment', 'rating')

movie/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from .models import *
from .forms import *
from django.db.models import Avg
# Create your views here.

def home(request):
    query = request.GET.get("title")
    allMovie = None
    if query:
        allMovie = Movie.objects.filter(name__icontains=query)
    else: 
        allMovie = Movie.objects.all()
    
    context = {
        "movies": allMovie,
    }


    return render(request, 'movie/index.html', context)

def details(request, id):
    movie = Movie.objects.get(id=id)
    reviews = Review.objects.filter(movie=id).order_by("-comment")
    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    
    
    if average == None:
        average = 0
    average = round(average, 1)
    context = {
        "movie": movie,
        "reviews": reviews,
        "average": average,
    }

    return render(request, 'movie/details.html', context)



def add_movie(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:

            if request.method == "POST":
                form = MovieForm(request.POST or None)

                #check for if forms is valid
                if form.is_valid():
                    data = form.save(commit = False)
                    data.save()
                    return redirect("movie:home")

            else:
                form = MovieForm()
            return render(request, 'movie/addmovies.html', {"form": form, "controller": "Add Movies"})
        #if user is not admin
        else:
            return redirect("movie:home")
    # if user is not logged in
    #else:
    return redirect("user:login")


def update_movie(request, id):
    
    movie = Movie.objects.get(id=id)

    #form check
    if request.method == "POST":
        form = MovieForm(request.POST or None, instance=movie)

        #check for if forms is valid
        if form.is_valid():
            data = form.save(commit = False)
            data.save()
            return redirect("movie:details", id)
    
    else:
        form = MovieForm(instance=movie)
    return render(request, 'movie/addmovies.html', {"form": form,  "controller": "Update Movies"})


def delete_movie(request, id):
    
    movie = Movie.objects.get(id=id)

    #delete movie
    movie.delete()
    return redirect("movie:home")


#Review

def add_review(request, id):
    if request.user.is_authenticated:
        
        movie = Movie.objects.get(id=id)
        if request.method == "POST":
            
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.movie = movie
                data.save()
                return redirect("movie:details", id)

        else:
            form = ReviewForm()

        return render(request, 'movie/details.html', {"form": form})
    
    return redirect("user:login")

def edit_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        review = Review.objects.get(movie=movie, id=review_id)

        if request.user == review.user:
            if request.method == "POST":
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating > 10) or (data.rating < 0):
                        error = "Out of range. Select value from 0 to 10."
                        return render(request, 'movie/editreview.html', {"error": error, "form": form})
                    else:
                        data.save()
                        return redirect("movie:details", movie_id)
            else:
                form = ReviewForm(instance=review)
            return render(request, 'movie/editreview.html', {"form": form})
        else:
            return redirect("movie:details", movie_id)
  
    return redirect("user:login")

def delete_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        review = Review.objects.get(movie=movie, id=review_id)

        if request.user == review.user:
            review.delete()
        return redirect("movie:details", movie_id)
    else:        
        return redirect("user:login")             

def watchlist_add(request, movie_id):
    item_to_save = get_object_or_404(Movie, pk=movie_id)
    # Check if the item already exists in that user watchlist
    if Watchlist.objects.filter(user=request.user, item=movie_id).exists():
        #messages.add_message(request, messages.ERROR, "You already have it in your watchlist.")
        return HttpResponseRedirect(reverse("movie:home"))
    
    # Get the user watchlist or create it if it doesn't exists
    user_list, created = Watchlist.objects.get_or_create(user=request.user)
   
    # Add the item through the ManyToManyField (Watchlist => item)
    user_list.item.add(item_to_save)
    #messages.add_message(request, messages.SUCCESS, "Successfully added to your watchlist")
    obj = Watchlist.objects.get(user=request.user)
    watchlist= obj.item.all()
    for x in watchlist:
        print(x.name)
    return render(request, 'movie/watchlist.html', {'watchlist':watchlist})

def watchlist_del(request, movie_id):
    item_to_del = get_object_or_404(Movie, pk=movie_id)
    obj = Watchlist.objects.get(user=request.user)
    obj.item.remove(item_to_del)
    return redirect("movie:home")             

def watchlist_view(request):
    obj = Watchlist.objects.get(user=request.user)
    watchlist = obj.item.all()
    return render(request, 'movie/watchlist.html', {'watchlist':watchlist})

movie/templates/movie/addmovies.html
{% extends 'movie/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-content">
            <h3 class="text-center">{{ controller }}</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="{{ controller }}" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>
</div>

{% endblock %}

movie/templates/movie/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" href="{% static  'css/main.css' %}">
    <title>Online Movie Review System</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <a class="navbar-brand" href="{% url 'movie:home' %}">Online Movie Review System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'movie:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            
            
            {% if user.is_authenticated %}
            <li class="nav-item">
              <li class="nav-item">
                <a class="nav-link" href="#">{{ user.username }}</a>
              </li>
              {% if request.user.is_superuser %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'movie:add_movie' %}">Add Movie</a>
                </li>
              {% endif %}
              <li>
                <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
              </li>
              <li>
                <a class="nav-link" href="/watchlistview">WatchList</a>
              </li>
            </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user:register' %}">Register</a>
              </li>
            {% endif %}
          </ul>
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'movie:home' %}" >
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title" >
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

    {% block content %}

    {% endblock %}



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

movie/templates/movie/details.html
{% extends 'movie/base.html' %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
             <div class="col-md-4" >
                <img src= "{{movie.image}}" alt="{{ movie.name}}" class="img-fluid">
             </div>
        
             <div class="col-md-8">
                <h3 class="text-center">{{ movie.name}}</h3>
                <h5>Cast: {{ movie.cast }}</h5>
                <h5>description: {{ movie.description }}</h5>
                <h5>category: {{ movie.category}}</h5>
                <h5>rel_date: {{ movie.rel_date}} </h5>
                <h5>avg_rating: {{ average }}/10</h5>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'movie:watchlist_add' movie.id %}" class="btn btn-warning" onclick="return alert('Do you want to add this to watchlist?');">Add to WatchList</a>
                    {% if request.user.is_superuser %}
                        <a href="{% url 'movie:update_movie' movie.id %}" class="btn btn-warning">Edit Movie</a>
                        <a href="{% url 'movie:delete_movie' movie.id %}" class="btn btn-danger" onclick="return confirm('Are you sure!!!?');">Delete Movie</a>
                    {% endif %}
                {% endif %}
             </div>
            </div>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Add Reviews</h3>
            <form action="{% url 'movie:add_review' movie.id %}" method="POST">
                {% csrf_token %}
                <label for="comment">Review:</label>
                <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>
                
                <label for="rating">Rating</label>
                <input type="range" id="rangeInput" name="rating" min="0" max="10" value="0" step="0.5"
                    oninput="amount.value=rangeInput.value" >

                <output  name="amount"  id="amount" for="rangeInput" >0</output>
                <br>
                <input type="submit" value="Add Review" class="btn btn-danger">
            </form>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
                {% for review in reviews %}
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <h5 class="text-left">{{ review.user.username }}</h5>
                                    <h5>{{ review.rating }}</h5>
                                    {% if request.user == review.user %}
                                        <a href="{% url 'movie:edit_review' movie.id review.id %}">Edit</a>
                                        <a href="{% url 'movie:delete_review' movie.id review.id %}" onclick="return confirm('Are you sure!!!?');">Delete</a>
                                    {% endif %}
                                </div>
                                <div class="col-md-9">
                                    <p>{{ review.comment }}</p>
                                </div>
                            </div>
                        </div>
                    </div><br>
                  
                {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock %}

movie/templates/movie/editreview.html
{% extends 'movie/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-content">
            <h3 class="text-center">Edit Review</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                {% if error %}
                    <strong style="color: red;">{{ error }}</strong>
                {% endif %}<br>
                <input type="submit" value="Edit Review" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>
</div>

{% endblock %}

movie/templates/movie/index.html
{% extends 'movie/base.html' %}

{% block content %}

<div class="container">
    <br>
    <div class="card" id="backdrop">
        <div class="card-body">
            <div class="row">
                {% for movie in  movies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">

                            <img src="{{ movie.image }}" alt="" class="img-fluid" width="75%">
                            <h3 class="text-center">{{ movie.name }}</h3>
                                <i class="text-center">{{ movie.rel_date }} </i>
                                <br>
                                <a href="{% url 'movie:details' movie.id %}">Read more...</a>
                            </div>
                            
                        
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

movie/templates/movie/watchlist.html
{% extends 'movie/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card" >
        <div class="card-content">
            <h3 class="text-center">WatchList</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                            {% for movie in watchlist %}
                                <div class="card" id="backdrop" >
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-4" >
                                                <img src= "{{movie.image}}" alt="{{ movie.name}}" class="img-fluid" width="50%">
                                             </div>
                                            <div class="text-center">
                                                <h3 class="text-center">{{ movie.name }}</h3>
                                                <h5 class="text-center">rel_date: {{ movie.rel_date }} </h5>
                                                <h5>category: {{ movie.category}}</h5>
                                                <br>            
                                                <a href="{% url 'movie:watchlist_del' movie.id  %}" class="btn btn-danger" onclick="return confirm('Are you sure!!!?');">Delete</a>
                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div><br>
                              
                            {% endfor %}
                        </ul>
                    </div>
            </form>
        </div>
    </div>
</div>
</div>

{% endblock %}